#Uncomment for OSS deployment - when repo is public
#arch:
#  - arm64
#  - ppc64le
#  - s390x

#Travis environment setup
language:       ruby
os:             linux
dist:           focal
services:       docker

#Get entire repo history when cloning
#To get commits info, for use in git-restore-mtime in deploy.sh
git:
  depth:        false

#Emails to notify about build result
#Default unchanged, sends on success if previous build failed, and on every fail
notifications:
  email:
    recipients:
      - khalidzohair12@gmail.com
    on_success: always
    on_failure: always

#Before building for production, build for testing
#This builds base images (installing the dependencies inside them)
#These base images will be used later to further build for production
install:
  - docker build -t ziyadss/flickr-frontend-test -f frontend-Flickr/Dockerfile.dev frontend-Flickr
  - docker build -t ziyadss/flickr-backend-test -f flickr-backend/Dockerfile.dev flickr-backend

#Run tests on the base images, if successfull build further on them for production
script:
  - docker run -p 3000:3000 -e CI=true ziyadss/flickr-frontend-test
  - docker run -p 8000:8000 -e CI=true ziyadss/flickr-backend-test

  - docker build -t ziyadss/flickr-frontend frontend-Flickr
  - docker build -t ziyadss/flickr-backend flickr-backend

#If tests and production build succeed, deploy using deploy.sh
deploy:
  provider:     script
  script:       bash deploy.sh $DOCKER_ACCESS_KEY $DOCKER_ID $EC2_INSTANCE
  on:
    branch:     main
