version: "3"
services:
  front:
    image: ziyadss/flickr-frontend
    ports:
      - "3000:3000"
    depends_on: back
  back:
    image: ziyadss/flickr-backend
    volumes:
      - ./flickr-backend:/app
    ports:
      - "8000:8000"
    restart: on-failure

#This is the production running environment
