# Generated by Django 3.0.5 on 2021-06-04 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('is_public', models.BooleanField(default=True)),
                ('can_comment', models.CharField(choices=[('Only The Owner', 'Only The Owner'), ('People You Follow', 'People You Follow'), ('Any Flickr Member', 'Any Flickr Member')], default='Any Flickr Member', max_length=25)),
                ('can_addmeta', models.CharField(choices=[('Only The Owner', 'Only The Owner'), ('People You Follow', 'People You Follow'), ('Any Flickr Member', 'Any Flickr Member')], default='Any Flickr Member', max_length=25)),
                ('count_comments', models.PositiveIntegerField(default=0)),
                ('count_notes', models.PositiveIntegerField(default=0)),
                ('count_tags', models.PositiveIntegerField(default=0)),
                ('count_people_tagged', models.PositiveIntegerField(default=0)),
                ('count_favourites', models.PositiveIntegerField(default=0)),
                ('is_faved', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_taken', models.DateTimeField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('media_file', models.ImageField(upload_to=photo.models.upload_to)),
                ('photo_height', models.PositiveSmallIntegerField(blank=True)),
                ('photo_width', models.PositiveSmallIntegerField(blank=True)),
                ('photo_displaypx', models.PositiveSmallIntegerField()),
                ('rotated_by', models.PositiveSmallIntegerField(default=0)),
                ('group_count', models.PositiveIntegerField(blank=True, default=0)),
                ('faved_notification', models.BooleanField(default=True)),
                ('comment_notification', models.BooleanField(default=True)),
                ('note_notification', models.BooleanField(default=True)),
                ('tag_notification', models.BooleanField(default=True)),
                ('photo_gallery_notification', models.BooleanField(default=True)),
                ('photo_group_notification', models.BooleanField(default=True)),
                ('favourites', models.ManyToManyField(blank=True, related_name='post_favourite', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag_text', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to='photo.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleTagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_people_actions', to=settings.AUTH_USER_MODEL)),
                ('person_tagged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_tagged', to='photo.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('left_coord', models.PositiveSmallIntegerField()),
                ('top_coord', models.PositiveSmallIntegerField()),
                ('note_width', models.PositiveSmallIntegerField()),
                ('note_height', models.PositiveSmallIntegerField()),
                ('note_text', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_notes', to='photo.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('comment_text', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comments', to='photo.Photo')),
            ],
        ),
    ]
